const postsData = [
  {
    id: 1,
    title: "Thoughts on SoFi Technologies",
    date: "June 23, 2025",
    content: "SOFI is a key player in the fintech space, while the stock price has slowly risen, I feel as if the stock is still undervalued",
    comments: [],
    ticker: "SOFI",
  },
  {
    id: 2,
    title: "Robinhood - A Financial Tech Innovator",
    date: "June 23, 2025",
    content: "Robinhood has democratized trading, and has had an amazing rally lately. With all of the new products it is launching, can HOOD maintain its momentum? I think it may!",
    comments: [],
    ticker: "HOOD",
  },
  {
    id: 3,
    title: "Iris Energy’s Bitcoin Mining Future",
    date: "June 23, 2025",
    content: "Iris Energy’s focus on sustainable Bitcoin mining is amazing, plus it is enterening the energy field. With IREN’s stock tied to crypto trends, is it a solid long-term bet? Let’s discuss!",
    comments: [],
    ticker: "IREN",
  },
  {
    id: 4,
    title: "MicroStrategy’s Bitcoin Strategy",
    date: "June 23, 2025",
    content: "MicroStrategy’s heavy Bitcoin investments make MSTR a unique play. Is their all-in crypto approach brilliant or risky? I’m curious about your opinions!",
    comments: [],
    ticker: "MSTR",
  },
  {
    id: 5,
    title: "Shopify’s E-Commerce Dominance",
    date: "June 23, 2025",
    content: "Shopify continues to empower businesses with its e-commerce platform. It has quite a high valuation but SHOP’s growth is impressive, but can it sustain its high valuation? What do you think?",
    comments: [],
    ticker: "SHOP",
  },
  {
    id: 6,
    title: "Sea Limited’s Southeast Asia Play",
    date: "June 23, 2025",
    content: "Sea Limited’s expansion in gaming, e-commerce, and fintech across Southeast Asia is bold. SE faces regional challenges, but the potential is huge. What’s your view?",
    comments: [],
    ticker: "SE",
  },
];